### PR TITLE
Add qcd exa to theory.db as theory 798

### PR DESCRIPTION
**Pull request by niclaurenti**
Adding QCD EXA theory:
- `798` full QCD `EXA` theory

### CODE REVIEW

**Comment by niclaurenti** [comment]
@andreab1997 @giacomomagni @RoyStegeman you are keeping track of the numbering of the theories more than me. Are 800 and 801 free?

**Comment by RoyStegeman** [comment]
I think you should be able to use 798 and 799, I'm not aware of anyone else already having reserved theories

**Comment by giacomomagni** [comment]
> I think you should be able to use 798 and 799, I'm not aware of anyone else already having reserved theories

it should be okay, n3lo last at 797 and we are currently using 800 for polarized stuff.

**Comment by RoyStegeman** [comment]
Did you want to merge this?

**Comment by niclaurenti** [comment]
@RoyStegeman I delete the ``mixed'' theory and then yes

**Pull request merged**
