### PR TITLE
New plotting functions for MHOU

### PR DESCRIPTION
**Pull request by andreab1997**
Given that we will need several new kind of plots for the MHOU and N3LO papers, I suggest we collect here the new functions. @giacomomagni

CC: @scarlehoff

### CODE REVIEW

**Comment by giacomomagni** [comment]
@andreab1997 if you can (and know how to do it), would you mind replacing the label: `"NNLO-NLO Shift"` in `validphys2/src/validphys/theorycovariance/test.py` with somethingmore generic ?

**Comment by andreab1997** [comment]
> @andreab1997 if you can (and know how to do it), would you mind replacing the label: `"NNLO-NLO Shift"` in `validphys2/src/validphys/theorycovariance/test.py` with somethingmore generic ?

So of course something more generic is easy to have. Would you like something like "Shift"?

**Comment by giacomomagni** [comment]
> So of course something more generic is easy to have. Would you like something like "Shift"?

it would be great to have `order1 - order2 Shift` but not sure how difficult is. So I'm okay with anything.

**Comment by andreab1997** [comment]
> > So of course something more generic is easy to have. Would you like something like "Shift"?
> 
> it would be great to have `order1 - order2 Shift` but not sure how difficult is. So I'm okay with anything.

Yes indeed, this is what I am going to try first

**Comment by scarlehoff** [comment]
It would be great to remove the unused code in the `theorycovariance` module before adding more...

**Comment by andreab1997** [comment]
> It would be great to remove the unused code in the `theorycovariance` module before adding more...

I agree but this is here just to avoid rewriting code a lot of times. Once we will be sure about which plots we want to have in the papers I will close this and open another in which I will polish a bit the `theorycovariance` module and add all and only the relevant functions.

**Comment by andreab1997** [comment]
@scarlehoff I believe the theorycovariance module is cleaned now (there might be a few other lines of code that could be removed but most of the work is done). I would also like to address #1847, would you like me to do that here? Or, should I open another PR?

Also, if you have other suggestions regarding the `theorycovariance` module, please write them here (or in an issue).

**Comment by scarlehoff** [comment]
> would you like me to do that here? Or, should I open another PR?

I would say open a separate PR (but taking this one as the initial state) that way if something goes wrong it is easier to revert.

**Comment by scarlehoff** [comment]
Is this ready for review?

**Comment by andreab1997** [comment]
> Is this ready for review?

Regarding the cleaning yes, but it is not yet ready to be merged as I want at least to address #1847. If in the meanwhile you want to have a look, you are more than welcome

**Comment by scarlehoff** [comment]
If #1847 is the only thing missing it would be better in a separate PR (that starts from this one)

**Comment by RoyStegeman** [comment]
@achiefa and I noticed that `combine_by_type` is doing some weird things because the inputs are not ordered in the same way. `each_dataset_results_central_bytheory` is ordered by process while `dataset_names` follows the runcard order. I understand from @andreab1997 that this is not a problem since before using the covmat it is reordered in agreement with the experimental covmat, but it's certainly very confusing and worth correcting.

**Comment by andreab1997** [comment]
Given that this is now outdated and that the pull plots are now in #1910, I am closing this.

**Pull request closed without merging**
