### PR TITLE
Fix pseudodata indexing mismatch

### PR DESCRIPTION
**Pull request by siranipour**
This caused the indexing of the pseudodata to be messed up

### CODE REVIEW

**Comment by Zaharid** [comment]
@siranipour Actually I am not sure if it is free of trouble to change this: `dataset_inputs_loaded_cd_with_cuts` is used in the covmats module, where instead it is expected that it is ordered as  `data_input`. Maybe we should do one of:

  - Define a different provider as done in this pr, as done in this PR.
  - Have an index that doesn't reorder the inputs.

**Comment by siranipour** [comment]
Okay should be an easy fix

**Comment by Zaharid** [comment]
Also, would it be easy to add a test for this?

**Comment by Zaharid** [comment]
@scarlehoff I am going to  go ahead and say that this isn't failing twice in the same way because of cosmic rays.

**Comment by scarlehoff** [comment]
Interesting. It does seem to be random though.

**Comment by scarlehoff** [comment]
Sadly my line to copy the package also failed :__

**Comment by scarlehoff** [comment]
I still cannot reproduce it so here's your report: https://vp.nnpdf.science/Ki5hG87QQvusLVERrPUlFw==

**Review by Zaharid — APPROVED** [review]

**Pull request merged**
