### PR TITLE
Fixing logs of evolven3fit_new

### PR DESCRIPTION
**Pull request by andreab1997**
The logs of `evolven3fit_new` are broken. This is fixing it. 

@giacomomagni

### CODE REVIEW

**Comment by scarlehoff** [comment]
What do you mean by broken?

**Comment by andreab1997** [comment]
> What do you mean by broken?

It is not logging the information but just a  constant string

**Comment by scarlehoff** [comment]
Ah, ok. But the evolution does work. It is just the content of the log which is not useful, right?

**Comment by andreab1997** [comment]
> Ah, ok. But the evolution does work. It is just the content of the log which is not useful, right?

Yes exactly, the evolution is fine. It is just a logging problem

**Review by giacomomagni — APPROVED** [review]

**Review by giacomomagni — APPROVED** [review]

**Pull request merged**
