### PR TITLE
Enable python 3.9 and mamba build

### PR DESCRIPTION
**Pull request by scarlehoff**
As per https://github.com/NNPDF/nnpdf/issues/1458#issuecomment-958807144

If the workflow works I'll enable also 3.8 so that we have both for the time being.

### CODE REVIEW

**Comment by scarlehoff** [comment]
I'm waiting for the 3.8 fitbot and then I'll send the 3.9 fitbot to see whether there are any differences.

**Comment by scarlehoff** [comment]
Mm, the fit itself is ok and I seem to be able to run comparefit with python 3.9 so this cannot be merged yet. There's some package that it's not working correctly...

**Comment by Zaharid** [comment]
I am

> Mm, the fit itself is ok and I seem to be able to run comparefit with python 3.9 so this cannot be merged yet. There's some package that it's not working correctly...

Not sure I understand this.

**Comment by scarlehoff** [comment]
> Not sure I understand this.

I shouldn't write complex sentences too early in the morning. It's missing "but for the fit fails, so we cannot merge this yet".
I've downloaded the fit and I am able to run comparefits in my computer (and the fit looks ok, which makes sense because the test pass) so I need to compare my packages with the bot packages to see what created the problem.

**Comment by Zaharid** [comment]
FWIW the error is

```
   File "/usr/share/miniconda/envs/nnpdfenv/lib/python3.9/site-packages/validphys/covmats.py", line 391, in sqrt_covmat

    decomp = la.cholesky(correlation_matrix)
  File "/usr/share/miniconda/envs/nnpdfenv/lib/python3.9/site-packages/scipy/linalg/decomp_cholesky.py", line 88, in cholesky
    c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=True,
  File "/usr/share/miniconda/envs/nnpdfenv/lib/python3.9/site-packages/scipy/linalg/decomp_cholesky.py", line 17, in _cholesky
    a1 = asarray_chkfinite(a) if check_finite else asarray(a)
  File "/usr/share/miniconda/envs/nnpdfenv/lib/python3.9/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
```

It might be something with numpy or rather pandas.

**Comment by scarlehoff** [comment]
Doesn't seem to be the case though.

**Comment by RoyStegeman** [comment]
Is it a problem with python 3.9 or with boa? Since you changed both at the same time.

**Comment by scarlehoff** [comment]
I have no idea. I'm inclined to blame the cosmic rays though because the test passed with both 3.9 and boa.

**Comment by Zaharid** [comment]
@scarlehoff just to be clear, are you able to run comparefits with the equivalent package built locally? Also what is the difference with the fit above that passed?

**Comment by scarlehoff** [comment]
> @scarlehoff just to be clear, are you able to run comparefits with the equivalent package built locally? Also what is the difference with the fit above that passed?

I was able to run comparefits with a (dirty that I used for testing yesterday) 3.9 conda environment, but I checked the usual suspects (`numpy`, `pandas`, `scipy`) and the versions where those of the bot. So that's all I can say at the moment.

I have to create a fresh environment, built the package, redownload resources and test to be equivalent to what the bot did.

**Comment by scarlehoff** [comment]
> @scarlehoff just to be clear, are you able to run comparefits with the equivalent package built locally? Also what is the difference with the fit above that passed?

Now the answer is yes: https://vp.nnpdf.science/ILCPf1olSs-GWwDP_vDjdw==/

**Comment by Zaharid** [comment]
Uh.

Is there a difference between the fit that failed and the one that succeeded?

**Comment by scarlehoff** [comment]
> Is there a difference between the fit that failed and the one that succeeded?

No. Which should be the case (all packages should be the same, the only difference being whether the box is running in 3.8 or 3.9).

**Comment by scarlehoff** [comment]
So it was really due to cosmic rays...

**Comment by RoyStegeman** [comment]
I guess this is done now, right? Just remove the lines that save the package upon test failure. 

And do you want to run the tests for both 3.8 and 3.9, or just 3.9?

**Comment by scarlehoff** [comment]
> Just remove the lines that save the package upon test failure.

It might be useful in the future.

> And do you want to run the tests for both 3.8 and 3.9, or just 3.9?

Both, it's "free" (maybe not that free in Mac? We could skip that...) and we want to have packages for both.

**Comment by RoyStegeman** [comment]
> Both, it's "free" (maybe not that free in Mac? We could skip that...) and we want to have packages for both.

I think MacOS is free as well. At least it's not mentioned that it's the excepoiton to the first sentence: 
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions

**Comment by scarlehoff** [comment]
Not in terms of money but I think (I might be wrong) that while you can run many Linux actions in parallel, for Mac OS that's limited to something like 5 (and then if both 3.8 and 3.9 are active at the same time only two commits can be running at the same time instead of 5 of them).

**Comment by RoyStegeman** [comment]
> and then if both 3.8 and 3.9 are active at the same time only two commits can be running at the same time instead of 5 of them

This doesn't really seem very limiting for us.

**Comment by scarlehoff** [comment]
@Zaharid have a look at this and if you're ok with it merge, like and subscribe.

**Review by Zaharid — APPROVED** [review]

**Comment by Zaharid** [comment]
Thanks for this work!

As discussed I think we should move to conda forge in another PR and see how disruptive that is.

**Pull request merged**
