### PR TITLE
Raise an exception for wrongly loaded positivity or integrability datasets

### PR DESCRIPTION
**Pull request by scarlehoff**
Fixes user errors like #1582

### CODE REVIEW

**Comment by Zaharid** [comment]
I am thinking if this is limiting some interesting cases but can't think of any so this is probably fine for now.

I think it is good to think how we'd like these checks to look in the new commondata format, and also rethink how we'd like the special cases for cuts to work.

I think they would be based on capabilities rather than on e.g. naming conventions. For example it should be fine to use a "full" dataset as a positivity constraint (e.g. because we'd like to exclude it from the fit but still make sure the predictions are positive). I think that should work without e.g. having to rename the set, which we know is a pain. But of course if we try to compute the chi2 of a positivity only commondata that should fail saying that we don't have experimental data.

cc @enocera

**Review by Zaharid — APPROVED** [review]

**Comment by scarlehoff** [comment]
> For example it should be fine to use a "full" dataset as a positivity constraint (e.g. because we'd like to exclude it from the fit but still make sure the predictions are positive)

This would be actually useful, yes. I guess right now the hack exists by copying the `fktable` with a POS in front. But it would be nice to be able to do it hackless.

**Comment by felixhekhorn** [comment]
> This would be actually useful, yes. I guess right now the hack exists by copying the `fktable` with a POS in front. But it would be nice to be able to do it hackless.

just to say, that for pinefarm there is indeed no difference between a "normal" dataset and a "positivity" dataset

the current situation is:
- PDF positivity datasets have their own [generator](https://github.com/NNPDF/runcards/blob/master/pinefarm/external/positivity.py)
- DIS positivity datasets are ordinary yadism runcards with `NCPositivityCharge` in the obs card; actually it is a bit more complicated since I need to [detect this](https://github.com/NNPDF/runcards/blob/04572c4124fb1a379ef77805749d726f0cd6a3e9/pinefarm/external/yad.py#L39) and eventually [shut down TMC](https://github.com/NNPDF/runcards/pull/143#issuecomment-1218281454)
- DY positivity datasets are similar to DIS, in that they have a special configuration and act slightly different in the generation

however, the outcome is in any case just an ordinary pineappl grid, as for any dataset

**Comment by scarlehoff** [comment]
No, the grids are also equal from the vp points of view. But we want to know they are different because they are treated different (cuts are not applied, lagrange multipliers, no data associated).

Sadly at some point whether a dataset was positivity (or integrability) was defined by its name (INTEG or POS) and treated differently. Going forward we can burn a tag into the fktable metadata (would be trivial to add to pinefarm and might be relevant information anyway)

**Comment by felixhekhorn** [comment]
But wasn't @Zaharid thinking about using them in a flexible way? i.e. the fk table can be used both as "normal" and positivity table? (@Zaharid correct me, if I misunderstood) and so the information should not be burnt in, because it is dynamic?

**Comment by scarlehoff** [comment]
The information that it is a positivity fktable does not prevent you from using it in a flexible way. It just means that as soon as you try to do something that is not allowed you can catch it without having to resort to it being called "POS".

**Pull request merged**
