### PR TITLE
fix std_error function in MCStats class

### PR DESCRIPTION
**Pull request by RoyStegeman**
In #1522 we replaced self.data with self.error_members(), but did not update the `ddof` value accordingly.

### CODE REVIEW

**Comment by scarlehoff** [comment]
Thanks. Let's see whether it has a visible effect anywhere.

**Comment by RoyStegeman** [comment]
Hmm, I would have expected to at least be able to see the difference with only 16 replicas

**Comment by scarlehoff** [comment]
I'm surprised not many regressions failed. I guess the PDF errors are almost only used for the plots themselves so not many chances of having an effect.

**Comment by RoyStegeman** [comment]
It's just because our code is optimally tested. One and only one test per functionality 

Yes... That's why..

**Review by scarlehoff — APPROVED** [review]
I'm not going to write "I'm happy with it" because we have already proven scientifically that it brings misfortune.

**Pull request merged**
