### PR TITLE
Add theory_440 to theory.db

### PR DESCRIPTION
**Pull request by andreab1997**
Just added theory_440 (that is a copy of theory 400 only for `HERA` with the b threshold shifted by a factor 1.2) to the theory db. @enocera

### CODE REVIEW

**Review by enocera — CHANGES_REQUESTED** [review]
@andreab1997 The value of mb has not been changed, as far as I can see. I know that this is immaterial for all practical purposes, but shouldn't we multiply it by 1.2?

P.S. at some point we should get rid of this `theory.db` file and use the `<theoryid>.yaml` files instead.

**Comment by andreab1997** [comment]
> @andreab1997 The value of mb has not been changed, as far as I can see. I know that this is immaterial for all practical purposes, but shouldn't we multiply it by 1.2?
> 
> P.S. at some point we should get rid of this `theory.db` file and use the `<theoryid>.yaml` files instead.

Actually `mb` is ok, what should change is `kbThr` (in particular from `1.0` to `1.2`). Do you agree?

**Comment by enocera** [comment]
> Actually `mb` is ok, what should change is `kbThr` (in particular from `1.0` to `1.2`). Do you agree?

Yes, I do.

**Review by enocera — APPROVED** [review]

**Comment by scarlehoff** [comment]
Please rebase on top of master (which in practice mean, re-add theory_440 on top of master) to ensure that this is not removing a theory from the database (I'm guessing the conflict is theory 600 which was the last one added? Unless someone else added another one afterwards?)

**Comment by andreab1997** [comment]
Actually @giacomomagni already booked untill theory 520 so I will change the name of this theory to 521.

**Comment by scarrazza** [comment]
Tests performed, no needed anymore.

**Pull request closed without merging**
