### PR TITLE
Add the square_singlet activation function

### PR DESCRIPTION
**Pull request by scarlehoff**
With a check so that it can only be used as the final layer.

### CODE REVIEW

**Comment by RoyStegeman** [comment]
Ah wait, this is applied before the basis rotation so maybe a check should be added that you're indeed squaring the singlet elements?

**Comment by scarlehoff** [comment]
@RoyStegeman can I take the previous green tick as still applying?

This has been used for this fit: https://vp.nnpdf.science/TsABd61tS_OOMbRYxCcmlA==/

**Comment by RoyStegeman** [comment]
> This has been used for this fit: https://vp.nnpdf.science/TsABd61tS_OOMbRYxCcmlA==/

Did you also check in evol basis?

**Comment by scarlehoff** [comment]
What do you mean? It can only be used in the evolution basis.

**Comment by RoyStegeman** [comment]
But the plots in the report are all flavor basis, so they don't really help to see if this PR does what you want

**Review by RoyStegeman — APPROVED** [review]
Thanks for adding the checks

**Comment by scarlehoff** [comment]
>  so they don't really help to see if this PR does what you want

Ah! That's what you mean. Yes: https://vp.nnpdf.science/RqocL3BvSL698F2-3ytrAw==/Scales0_pdf_report_report.html#Scales0_pdf_report_PDFnormalize0_Basespecs1_PDFscalespecs1_plot_pdfs_Sigma

(although it only makes a real difference for the gluon tbh)

**Comment by RoyStegeman** [comment]
Thanks, I'm happy to merge

**Pull request merged**
