### PR TITLE
hyperopt runcard

### PR DESCRIPTION
**Pull request by APJansen**
I thought it would be useful to discuss this in a PR. I've added the runcard that we used for the hyperopt runs so far (please confirm I got the right one @Cmurilochem).
I just picked a name but this can of course change, as long as it refers to the paper in some way.

I think what needs to be done is:
- Add back the full hyperparameter space of the original hyperopt runcard
- Change the theory to 700, right?
- Update any legacy names

And of course before we do any serious runs, have everyone do a careful check that this is what we want to run.

### CODE REVIEW

**Comment by scarlehoff** [comment]
Let me update the runcard (and I'll deal with #1984 in the process)
I will also change the name since god only knows when 4.1 will happen.

**Comment by APJansen** [comment]
Haha yes I figured, didn't know what other else to name it though. Thanks!

**Comment by Cmurilochem** [comment]
> Let me update the runcard (and I'll deal with #1984 in the process) I will also change the name since god only knows when 4.1 will happen.

Thanks @scarlehoff!

**Comment by scarlehoff** [comment]
Done. You can see I'm not that good with names.

**Comment by APJansen** [comment]
Haha great, it runs! Thanks :)

**Comment by Cmurilochem** [comment]
> Haha great, it runs! Thanks :)

It also resolved for me
```
def get_experimental_data(dataset_name="NMC_NC_NOTFIXED_P_EM-SIGMARED", theoryid=399):
    """Get experimental data set using validphys.

    Returns a list defined by the data set as
    `validphys.core.DataGroupSpec`.
    """
    loader = Loader()
    ds = loader.check_dataset(dataset_name, theoryid=theoryid, cuts="internal", variant="legacy")
    return loader.check_experiment("My DataGroupSpec", [ds])
```
But I had to add `variant="legacy"` as done in the runcard. Thanks you!

**Comment by APJansen** [comment]
@scarlehoff I do still get warnings about Apfelcomb being used, and to update the commondata file. Is that important, and how to update it?

[WARNING]: Apfelcomb key is being used to read [('CMS_TTB_8TEV_2D_TTM_TRAP',), ('CMS_TTB_8TEV_2D_TTM_TRAP_TOT',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLAS_TTB_8TEV_LJ_TRAP',), ('ATLAS_TTB_8TEV_LJ_TRAP_TOT',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLAS_TTB_8TEV_LJ_TTRAP',), ('ATLAS_TTB_8TEV_LJ_TTRAP_TOT',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLAS_TTB_8TEV_2L_TTRAP',), ('CMSTTBARTOT8TEV-TOPDIFF8TEVTOT',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('CMSTOPDIFF8TEVTTRAPNORM-TOPDIFF8TEVTTRAP',), ('CMSTOPDIFF8TEVTTRAPNORM-TOPDIFF8TEVTOT',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLASZPT8TEVMDIST-ATLASZPT8TEV-MLLBIN1_ptZ', 'ATLASZPT8TEVMDIST-ATLASZPT8TEV-MLLBIN2_ptZ', 'ATLASZPT8TEVMDIST-ATLASZPT8TEV-MLLBIN3_ptZ', 'ATLASZPT8TEVMDIST-ATLASZPT8TEV-MLLBIN4_ptZ', 'ATLASZPT8TEVMDIST-ATLASZPT8TEV-MLLBIN6_ptZ')], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLAS_DY_2D_8TEV_LOWMASS-ATLAS_DY_2D_8TEV-BIN1_rapidity', 'ATLAS_DY_2D_8TEV_LOWMASS-ATLAS_DY_2D_8TEV-BIN2_rapidity', 'ATLAS_DY_2D_8TEV_LOWMASS-ATLAS_DY_2D_8TEV-BIN3_rapidity', 'ATLAS_DY_2D_8TEV_LOWMASS-ATLAS_DY_2D_8TEV-BIN4_rapidity', 'ATLAS_DY_2D_8TEV_LOWMASS-ATLAS_DY_2D_8TEV-BIN5_rapidity', 'ATLAS_DY_2D_8TEV_LOWMASS-ATLAS_DY_2D_8TEV-BIN6_rapidity', 'ATLAS_DY_2D_8TEV_LOWMASS-ATLAS_DY_2D_8TEV-BIN7_rapidity')], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('D0ZRAP-D0_ZRAP_MCgrid_500M',), ('D0ZRAP-D0_ZNORM_MCgrid_500M',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM-aMCfast_obs_0', 'ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM-aMCfast_obs_1', 'ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM-aMCfast_obs_2'), ('ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM-ATLAS_SINGLETOP_TCH_R_7TEV_TB',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM-aMCfast_obs_0', 'ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM-aMCfast_obs_1', 'ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM-aMCfast_obs_2'), ('ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM-ATLAS_SINGLETOP_TCH_R_7TEV_T',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM-aMCfast_obs_0', 'ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM-aMCfast_obs_1', 'ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM-aMCfast_obs_2'), ('ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM-ATLAS_SINGLETOP_TCH_R_8TEV_TB',)], please update the commondata file
[WARNING]: Apfelcomb key is being used to read [('ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM-aMCfast_obs_0', 'ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM-aMCfast_obs_1', 'ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM-aMCfast_obs_2'), ('ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM-ATLAS_SINGLETOP_TCH_R_8TEV_T',)], please update the commondata file

**Comment by scarlehoff** [comment]
That has nothing to do with the runcard, it is the data itself that need to be updated so nothing to be worried about.

**Comment by APJansen** [comment]
As in we ignore it completely because the data isn't available yet, or do we need to update our local data before running?

**Comment by scarlehoff** [comment]
Nono, everything is up to date.
it looks more scary than it is so that people implementing new data don't use these features.

**Pull request merged**
