### PR TITLE
Fix callers of group_chi2_table

### LINKED ISSUE #1520: covariance_matrix_plot runcard fails when executing procs_chi2_table
Running the covariance_matrix_plot runcard fails when entering in the function `groups_chi2_table` https://github.com/NNPDF/nnpdf/blob/9840fc69dfcbcf25ebb30236916c4f1fc65a1785/validphys2/src/validphys/results.py#L666  This could be linked to the wrong shape of `groups_each_dataset_chi2` as constructed by https://github.com/NNPDF/nnpdf/blob/9840fc69dfcbcf25ebb30236916c4f1fc65a1785/validphys2/src/validphys/results.py#L663

### PR DESCRIPTION
**Pull request by Zaharid**
Commit 79604bd had introduced a level of indirection on the inputs of
groups_chi2_table to make sure that the data wasn't being reshuffled too
much. This however was not propagated to the actions that internally
made use of that functionality, of which there are three.

Fix the simpler one to use the original action with the right grouping
and add an additional collect over processes for the ones in the theory
covariance matrix module.

Closes #1520.

### CODE REVIEW

**Comment by andreab1997** [comment]
I tried running the following runcard
```
meta:
   author: Andrea Barontini
   keywords: [theory uncertainties, 9-point]
   title: NLO 9-point variations for 1 process type - DIS CC

default_theory:
   - theoryid: 163

theoryid: 163
point_prescription: '9 point'

theoryids:
   from_: scale_variation_theories


dataspecs:
        - theoryid: 163
          speclabel: $(\xi_F,\xi_R)=(1,1)$
        - theoryid: 177
          speclabel: $(\xi_F,\xi_R)=(2,1)$
        - theoryid: 176
          speclabel: $(\xi_F,\xi_R)=(0.5,1)$
        - theoryid: 179
          speclabel: $(\xi_F,\xi_R)=(1,2)$
        - theoryid: 174
          speclabel: $(\xi_F,\xi_R)=(1,0.5)$
        - theoryid: 180
          speclabel: $(\xi_F,\xi_R)=(2,2)$
        - theoryid: 173
          speclabel: $(\xi_F,\xi_R)=(0.5,0.5)$
        - theoryid: 175
          speclabel: $(\xi_F,\xi_R)=(2,0.5)$
        - theoryid: 178
          speclabel: $(\xi_F,\xi_R)=(0.5,2)$

normalize_to: 1

fit: 190315_ern_nlo_central_163_global
use_cuts: "fromfit"

pdf:
    from_: fit


dataset_inputs:
  - dataset: CHORUSNU
  - dataset: CHORUSNB
  - dataset: NTVNUDMN
  - dataset: NTVNBDMN
  - dataset: HERACOMBCCEM
  - dataset: HERACOMBCCEP

template: template_matrix_plots.md

dataset_report:
   meta: Null
   template_text: |
      ## Scale variations as a function of the kinematics for {@dataset_name@}
      {@plot_fancy_dataspecs@}

actions_:
  - report(main=true)

 ```
and it does not result in an error anymore. Anyway it looks like that the two tables of the output report (**Experimental chi2 by dataset** and **Total chi2 by dataset**) are grouped in a different way (the first by experiment and the second by process) despite the fact that they are generated by the same function (_groups_chi2_table_). Looking into that I noticed that the function is actually called twice but in the first case _groups_data_ has three entries corresponding to the experiments and in the second case it has only one entry corresponding to the only process (DIS CC). Is this a bug or am I missing an entry in the runcard? @Zaharid

**Comment by andreab1997** [comment]
> I tried running the following runcard
> 
> ```
> meta:
>    author: Andrea Barontini
>    keywords: [theory uncertainties, 9-point]
>    title: NLO 9-point variations for 1 process type - DIS CC
> 
> default_theory:
>    - theoryid: 163
> 
> theoryid: 163
> point_prescription: '9 point'
> 
> theoryids:
>    from_: scale_variation_theories
> 
> 
> dataspecs:
>         - theoryid: 163
>           speclabel: $(\xi_F,\xi_R)=(1,1)$
>         - theoryid: 177
>           speclabel: $(\xi_F,\xi_R)=(2,1)$
>         - theoryid: 176
>           speclabel: $(\xi_F,\xi_R)=(0.5,1)$
>         - theoryid: 179
>           speclabel: $(\xi_F,\xi_R)=(1,2)$
>         - theoryid: 174
>           speclabel: $(\xi_F,\xi_R)=(1,0.5)$
>         - theoryid: 180
>           speclabel: $(\xi_F,\xi_R)=(2,2)$
>         - theoryid: 173
>           speclabel: $(\xi_F,\xi_R)=(0.5,0.5)$
>         - theoryid: 175
>           speclabel: $(\xi_F,\xi_R)=(2,0.5)$
>         - theoryid: 178
>           speclabel: $(\xi_F,\xi_R)=(0.5,2)$
> 
> normalize_to: 1
> 
> fit: 190315_ern_nlo_central_163_global
> use_cuts: "fromfit"
> 
> pdf:
>     from_: fit
> 
> 
> dataset_inputs:
>   - dataset: CHORUSNU
>   - dataset: CHORUSNB
>   - dataset: NTVNUDMN
>   - dataset: NTVNBDMN
>   - dataset: HERACOMBCCEM
>   - dataset: HERACOMBCCEP
> 
> template: template_matrix_plots.md
> 
> dataset_report:
>    meta: Null
>    template_text: |
>       ## Scale variations as a function of the kinematics for {@dataset_name@}
>       {@plot_fancy_dataspecs@}
> 
> actions_:
>   - report(main=true)
> ```
> 
> and it does not result in an error anymore. Anyway it looks like that the two tables of the output report (**Experimental chi2 by dataset** and **Total chi2 by dataset**) are grouped in a different way (the first by experiment and the second by process) despite the fact that they are generated by the same function (_groups_chi2_table_). Looking into that I noticed that the function is actually called twice but in the first case _groups_data_ has three entries corresponding to the experiments and in the second case it has only one entry corresponding to the only process (DIS CC). Is this a bug or am I missing an entry in the runcard? @Zaharid

I found that this problem is related to these three collect
https://github.com/NNPDF/nnpdf/blob/3fa10e6dae35623ec658e9d0553c6d28030d7d87/validphys2/src/validphys/results.py#L184
https://github.com/NNPDF/nnpdf/blob/3fa10e6dae35623ec658e9d0553c6d28030d7d87/validphys2/src/validphys/results.py#L663
https://github.com/NNPDF/nnpdf/blob/3fa10e6dae35623ec658e9d0553c6d28030d7d87/validphys2/src/validphys/results.py#L803
which groups data "by_metadata". However the theory+experimental table is done by the function 
https://github.com/NNPDF/nnpdf/blob/3fa10e6dae35623ec658e9d0553c6d28030d7d87/validphys2/src/validphys/theorycovariance/output.py#L27
which calls groups_chi2_table with other inputs.
Changing "by_metadata" to "by_process" in the three collects above fixes the problem but I am not sure this is the right way of fixing it. @Zaharid

**Comment by andreab1997** [comment]
> @andreab1997 It should work so that actions used elsewhere such as `groups_data` are not affected, for example by defining new collects by process. It would be good if you could do that, e.g. by pushing to this PR and test around.

@Zaharid yes, you're right. I've defined new collects for groups_data and groups_chi2 (but not for groups_each_dataset_chi2 because it is only used here). 
I have also removed the group itself from the table because I believe it is misleading to have on the same level groups and datasets belonging to some group. I tested with the same runcard I posted before and it is working.

**Comment by scarlehoff** [comment]
We have been looking at this functions and I wonder whether it doesn't make more sense to scratch them all and use what we use normally i.e., `dataspecs_chi2_table`, so that we don't have to play any tricks and the grouping is selected in the runcard with `metadata_group`?

**Comment by Zaharid** [comment]
Is this good to merge?

**Comment by scarlehoff** [comment]
I would need to go through it, the server was down so I couldn't even run reports :_ I'll test it next week.

**Review by scarlehoff — APPROVED** [review]
I think this is fine https://vp.nnpdf.science/UggLD0bKRouUZHnBOKsBfQ==/

other than the fact that the table header says group when it is actually datasets but that's not what this PR is fixing. Once it's merged we can open a new issue with that.

**Comment by Zaharid** [comment]
Great, thanks.

**Pull request merged**
