### PR TITLE
update pineappl dependency to 0.6.2

### PR DESCRIPTION
**Pull request by RoyStegeman**
There were some bugfixes in pineappl since 0.5.8. Not sure if they affect anything we do in this repo but we may as well update it.

### CODE REVIEW

**Comment by scarlehoff** [comment]
If tests pass I'm happy with this.

However, just to make sure... this last version of pineappl is compatible with eko 0.14 ? (cc @AleCandido @cschwan @felixhekhorn) It should not matter for the nnpdf code, but just so that we make sure that people have a conda environment in which the different tools can talk with each other.

**Comment by AleCandido** [comment]
> However, just to make sure... this last version of pineappl is compatible with eko 0.14 ? (cc @AleCandido @cschwan @felixhekhorn) It should not matter for the nnpdf code, but just so that we make sure that people have a conda environment in which the different tools can talk with each other.

The PineAPPL interface we use has to be actually compatible with Pineko, that is making use of it.
There is also a direct interface between PineAPPL and EKO, that allows one to use the CLI, but this is not used in the Pineline (and it might be slightly broken because of the fix of the introduction of `matching_order` in the theory card, but I guess that it would just be ignored).

**Comment by RoyStegeman** [comment]
This PR doesn't change much other than that it pins a lower bound. In practice 0.6.2 is already being downloaded in most cases: https://github.com/NNPDF/nnpdf/actions/runs/6862782721/job/18661228431#step:6:969

**Review by scarlehoff — APPROVED** [review]
Perfect then.

**Pull request merged**
