### PR TITLE
Updates to the NNPDF docs

### PR DESCRIPTION
**Pull request by mariaubiali**
Hi all, 
I changed initial page, added new bib references and added instructions for installation from source on M3. This is just the beginning, any suggestions for extra things to modify are more than welcome.

### CODE REVIEW

**Comment by RoyStegeman** [comment]
Thanks @mariaubiali. Since you're making changes to the people in the collaboration, could you please also update Zahari's position?

**Comment by mariaubiali** [comment]
Thanks @RoyStegeman, well spotted, done! I have moved Zahari from current to past and added info on his current position

**Comment by Radonirinaunimi** [comment]
Thanks @mariaubiali! Given that this installation now works for all M macs, could you also please remove the M1/M2 section?

**Comment by scarlehoff** [comment]
Before merging this, let's test a bit the python 3.12 installation https://github.com/NNPDF/nnpdf/pull/1989
(I'd like to check that the change in reportengine won't have unintended consequences)

Also, since now we have a pineappl package also for Apple Silicon we can collapse the development installation for both mac and linux into just what's in this PR.

**Comment by mariaubiali** [comment]
Thanks @Radonirinaunimi I have removed that paragraph and now have "Installation from source on M1-M2-M3 Mac". Could someone check if the section above "Installation from Source" is still up-to-date?

**Comment by RoyStegeman** [comment]
> Could someone check if the section above "Installation from Source" is still up-to-date?

Thanks for asking. That's still fine.

**Comment by RoyStegeman** [comment]
I updated the docs a little bit. I now mention the `nolha` option, but I'm not sure we should since if it's in the docs we may have to provide support for it.

**Review by RoyStegeman — APPROVED** [review]

**Pull request merged**
