### PR TITLE
Add produce_eko_photon to evolven3fit_new

### PR DESCRIPTION
**Pull request by niclaurenti**
PR for adding `produce_eko_photon` in `evolven3fit_new`

### CODE REVIEW

**Review by andreab1997 — CHANGES_REQUESTED** [review]
It looks ok but please instead of branching in `construct_eko_cards`, just make another function for the photon. At the end in `construct_eko_cards` you are doing a lot of different things so it is probably better to have another function. All the things that instead are in common you can put in yet another function to be called in both cases.

**Comment by niclaurenti** [comment]
> It looks ok but please instead of branching in `construct_eko_cards`, just make another function for the photon. At the end in `construct_eko_cards` you are doing a lot of different things so it is probably better to have another function. All the things that instead are in common you can put in yet another function to be called in both cases.

Actually the branching `produce_eko_photon` happens only in three points. I did it like this exactly because there were common blocks of code that I had to copy paste, and I didn't want to add a lot of functions for those blocks

**Comment by scarlehoff** [comment]
I agree with @andreab1997 I think it is better to have different functions (and then lift some of the common functionality to wrappers) rather than so many branches.

**Review by andreab1997 — APPROVED** [review]
Good for me!

**Pull request merged**
