### PR TITLE
Collecting over cuts context for pseudodata

### PR DESCRIPTION
**Pull request by siranipour**
The reason the bug in https://github.com/NNPDF/nnpdf/issues/1414 happened was because we were collecting over an environment that was over specified. This does beg the question whether we still want to fix the point raised in #1414 in light of #1413

### CODE REVIEW

**Comment by Zaharid** [comment]
I think we want these fixes until we say we don't want them any longer :)

**Comment by Zaharid** [comment]
I don't think this is working though. It seems to be getting stuck in a loop.

**Review by Zaharid — APPROVED** [review]

**Review by Zaharid — CHANGES_REQUESTED** [review]
Hold on

**Comment by siranipour** [comment]
Old style fits are now supported too

**Review by Zaharid — APPROVED** [review]

**Pull request merged**
