### PR TITLE
[WIP] Testing problems with the bot

### PR DESCRIPTION
**Pull request by scarlehoff**
Please, ignore this branch. I'm just having a look at the fitbot.

Dr_UtZXUwAEjm7H

### CODE REVIEW

**Comment by scarlehoff** [comment]
Hi @andreab1997 

If I remove the restriction https://github.com/NNPDF/nnpdf/pull/1662/commits/647732ad0b4d6581275cbd83e4be60844a95cf18, the bot tries again to install an old version of the fit and that one works.

So I guess there is a reason why `conda` is avoiding your version. The problem now is to find out what that reason is. I recommend you use this branch for testing so that you don't do a lot of commits in the other one.

@AleCandido I'm guessing that it has to do with numpy/numba? Maybe it actually makes sense to update the branch to the latest version of eko? (even if not using all the features)

**Comment by andreab1997** [comment]
> Hi @andreab1997
> 
> If I remove the restriction [647732a](https://github.com/NNPDF/nnpdf/commit/647732ad0b4d6581275cbd83e4be60844a95cf18), the bot tries again to install an old version of the fit and that one works.
> 
> So I guess there is a reason why `conda` is avoiding your version. The problem now is to find out what that reason is. I recommend you use this branch for testing so that you don't do a lot of commits in the other one.
> 
> @AleCandido I'm guessing that it has to do with numpy/numba? Maybe it actually makes sense to update the branch to the latest version of eko? (even if not using all the features)

Yes, thisi is exactly what we were fighting some months ago and the reason why at a certain point a forced the installation of the branch. However we never really understood the reason because, once installed, that branch works perfectly fine.

**Comment by scarlehoff** [comment]
> once installed, that branch works perfectly fine

But this is no longer the case :(

**Comment by scarlehoff** [comment]
```
The following packages will be UPDATED:
[3312](https://github.com/NNPDF/nnpdf/actions/runs/3947148149/jobs/6755636650#step:8:3313)

[3313](https://github.com/NNPDF/nnpdf/actions/runs/3947148149/jobs/6755636650#step:8:3314)
  libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-12.2.0-h46fd767_19 
[3314](https://github.com/NNPDF/nnpdf/actions/runs/3947148149/jobs/6755636650#step:8:3315)

[3315](https://github.com/NNPDF/nnpdf/actions/runs/3947148149/jobs/6755636650#step:8:3316)
The following packages will be DOWNGRADED:
[3316](https://github.com/NNPDF/nnpdf/actions/runs/3947148149/jobs/6755636650#step:8:3317)

[3317](https://github.com/NNPDF/nnpdf/actions/runs/3947148149/jobs/6755636650#step:8:3318)
  lz4-c                                    1.9.4-h6a678d5_0 --> 1.9.3-h295c915_1
```

**Pull request closed without merging**
