### PR TITLE
Implementation of ATLAS_WCHARM_7TEV in the new format

### PR DESCRIPTION
**Pull request by achiefa**
Re-implementation of the ATLAS_WJ_8TEV in the new commondata format.

$(x, Q^2)$ map and data-theory comparison
=================================
Legacy implementation: [[default](https://vp.nnpdf.science/x97WpnYMSMWU5Jvs2Q-v4Q==)], [[sys_10](https://vp.nnpdf.science/sOCHUXQSSNypXAxzprb-qg==)]
New implementation: [[default](https://vp.nnpdf.science/1ssJm5mfSKqPXvfXe0Bxmw==)]

### CODE REVIEW

**Comment by achiefa** [comment]
I have implemented the default variant for this dataset. See the description of the PR above for the $(x,Q^2)$ map and the data-theory comparison. The chi2's are unchanged between the two implementations.

RE the t0 matrices, they are the same between the new implementation and the legacy variant :grimacing:
Screenshot 2024-12-04 at 09 16 43

There is one thing that is still missing though. In the legacy implementaion, there is a `sys_10` variant which accounts for two additional systematic uncertainties dubbed `SCALEVAR`. @enocera, @scarlehoff , do you know how to reconstruct these two additional sources?

**Comment by scarlehoff** [comment]
> RE the t0 matrices, they are the same between the new implementation and the legacy variant 😬

Hooray!

> There is one thing that is still missing though. In the legacy implementaion, there is a sys_10 variant which accounts for two additional systematic uncertainties dubbed SCALEVAR. @enocera, @scarlehoff , do you know how to reconstruct these two additional sources?

These are 3pt scale variations because we don't have NNLO corrections for this data.
Tbh, I would say these are obsolete in the new implementation since if we want to add theoretical uncertainties we should do it through a theory covmat, do you agree @enocera ?

**Comment by achiefa** [comment]
@scarlehoff gotcha. Let's wait for the tests to finish then.

**Comment by enocera** [comment]
@achiefa Please forget about the `sys_10` variant. This is indeed obsolete.

**Review by scarlehoff — APPROVED** [review]

**Comment by scarlehoff** [comment]
I'll wait for #2226 to be merged and then I'll merge this.

**Pull request merged**
