### PR TITLE
[WIP][New commondata format] DYE866R 2001

### PR DESCRIPTION
**Pull request by tgiani**
As the title says. Following the old implementation the kinematic variables are y, M and sqrt(s), where y is computed from xF and M. Need to check y definition.

The implementation for the 2003 data, which should be the dataset DYE866P, will be done in a separate PR

### CODE REVIEW

**Comment by enocera** [comment]
@tgiani May I ask you a favour: can you please have a single PR with ALL the DY data, instead of one PR for each data set?

**Comment by tgiani** [comment]
@enocera sure. If you prefer a single PR for me there is no difference

**Comment by enocera** [comment]
I definitely do. Thanks.

**Comment by tgiani** [comment]
ok, I ll move everything in one

**Pull request merged**
