### PR TITLE
Add integrability datasets for valence pdfs

### PR DESCRIPTION
**Pull request by RoyStegeman**
Adds datasets with a single point at 1e-9 to ensure integrability even if the preprocessing function is removed. 

The corresponding FK table has been added (only) to theory 200.

### CODE REVIEW

**Comment by tgiani** [comment]
@RoyStegeman will look at this asap, sorry

**Comment by RoyStegeman** [comment]
Thanks, and no worries, I was planning to remind you during the code meeting. Did Giacomo mention this PR? I believe I mentioned it to him today 😅

**Comment by tgiani** [comment]
yes @giacomomagni told me off. Sorry, I saw it and then I completely forgot. I ll review it tomorrow

**Comment by RoyStegeman** [comment]
Haha no worries, and thanks

**Review by tgiani — APPROVED** [review]

**Comment by RoyStegeman** [comment]
Yes I tried that as well, but it looked a bit overly restrictive, though possibly playing a bit with the maxlambda might solve that. But given that a single point at 1e-9 gives the desired behaviour, it is good enough for now.

**Pull request merged**
