### PR TITLE
[WIP] NNPDF data package

### PR DESCRIPTION
**Pull request by comane**
This PR addresses #1942

In this draft, the `validphys/datafiles` are moved into a directory `nnpdf_data` with it's own `pyproject.toml`.

### CODE REVIEW

**Comment by scarlehoff** [comment]
Since we are removing after the tag C++/libnnpdf/evolven3fit the problems in the tests might be resolves by that.

**Comment by scarlehoff** [comment]
This looks good to me. The only thing is leave `disp_theory.py` in the vp/datafiles folder (we can deal with the theory later), let's do only data for now.
This is a good starting point tbh, if you apply the changes to current master we can have the stuff already in that folder in the root of the repository and then in a subsequent PR we create a specific package to install it separately from the rest of the code.

Eventually we can move the parser also there but that can be yet another pr.

**Comment by scarlehoff** [comment]
You probably want also to set a minimum version of ruamel to avoid the need for the compat module

**Comment by comane** [comment]
Taken care of in #2009

**Pull request closed without merging**
