### PR TITLE
NNPDF data package

### PR DESCRIPTION
**Pull request by comane**
This PR addresses #1942 

The `validphys/datafiles` are moved into a directory `nnpdf_data` with it's own `pyproject.toml`.

### CODE REVIEW

**Comment by comane** [comment]
#1965

**Comment by comane** [comment]
Why are the pyproject.toml files not displayed in the "Files Changed"?

**Comment by scarlehoff** [comment]
I think there's too many files changed (due to moving the files from one folder to the other).

It would be good to add here the excludes that are in the main nnpdf pyproject https://github.com/NNPDF/nnpdf/blob/157c37b111d5d45f822113e2da996c933506cf84/nnpdf_data/pyproject.toml#L24

so that rawdata and filters are not installed.

**Review by scarlehoff — APPROVED** [review]
Thank you very much!

**Pull request merged**
