### PR TITLE
Scale variation updated theory cards  polarised CC DY

### PR DESCRIPTION
**Pull request by ggvanseev**
The updated theory cards for the the polarised charged current DY.

  - theoryid: 822
    variations:
      # (xif, xir)
      (0.5, 0.5): 851
      (0.5, 1): 852
      (0.5, 2): 853
      (1, 0.5): 854
      (1, 1): 822
      (1, 2): 855
      (2, 0.5): 856
      (2, 1): 857
      (2, 2): 858

### CODE REVIEW

**Comment by Radonirinaunimi** [comment]
@ggvanseev, @giacomomagni, let's adopt the new naming conventions from now on.

**Comment by RoyStegeman** [comment]
Please use the new theorycard format, so e.g. no deprecated keys

**Comment by RoyStegeman** [comment]
Have a look at the `TheoryCard` class, if something isn't clear @Radonirinaunimi will be able to explain it

Also please add the variations to the `Comments` key

**Comment by ggvanseev** [comment]
The new theory runcard format seems to be already satisfied, unless there are changes beyond name and type changes

**Comment by ggvanseev** [comment]
Thanks for the clarification, I will ask @Radonirinaunimi more about it

**Comment by ggvanseev** [comment]
This is moved to another branch, due to the forking being inconvenient #2123

**Pull request closed without merging**
