### PR TITLE
Photon lo new

### PR DESCRIPTION
**Pull request by niclaurenti**
I just opened a new PR for #2040 since I rebased master but something was giving problems then I merged

### CODE REVIEW

**Comment by scarlehoff** [comment]
Thanks. Once we have the NLO and NNLO QED variants I'll rerun the LO to test this branch.

Btw, could you have a look at #2067 ?

Basically to make sure that the theories there are what you used to generate the ekos and fktables!

**Review by scarlehoff — APPROVED** [review]
Seems to run ok

**Comment by niclaurenti** [comment]
> Seems to run ok

Great. Do you already have a fit? Is it reasonable?

**Comment by scarlehoff** [comment]
I've done only one replica.

It is LO so the results are by definition not reasonable at all..

**Pull request merged**
