### PR TITLE
Top data fixes

### PR DESCRIPTION
**Pull request by enocera**
This PR addresses #1576 and #1600. A spurious line in the QCD K-factors for `CMS_TTB_DIFF_13TEV_2016_2L_TTMNORM` was removed. A filter rule was added to remove the last bin of the `ATLAS_TOPDIFF_DILEPT_8TEV_TTMNORM` and `ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM` distributions, which is linearly dependent from the other bins.

### CODE REVIEW

**Comment by enocera** [comment]
@J-M-Moore Let me fix the code so that tests are passed.

**Comment by RoyStegeman** [comment]
@enocera the tests fail an overfit_metric test in the master branch. To avoid this you may want to rebase to 07712b78c2df969b59ae9c9b13f3776b648486ab. Apologies for the inconvenience.

**Comment by enocera** [comment]
Ah, thanks.

**Comment by enocera** [comment]
@J-M-Moore Approval of this PR would be greatly appreciated.

**Review by J-M-Moore — APPROVED** [review]
All looks good to me! Thanks for sorting this out Emanuele, sorry it was a bit fiddly to merge!

**Pull request merged**
